force-app/main/default/objects/Case/fields/vlocity_ps__PSCaseId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PSCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Case</label>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_ps__PartyId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>One-to-One relationship to Party Object</description>
    <label>Party</label>
    <referenceTo>vlocity_ps__Party__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Court_Hearing_Outcome__c/Court_Hearing_Outcome__c.object-meta.xml
<CustomObject>
    <label>Court Hearing Outcome</label>
    <nameField>
        <label>Court Hearing Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Court Hearing Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Court_Hearing_Outcome__c/fields/Ongoing_Case__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ongoing Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>vlocity_ps__Case__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Child Welfare</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Court Hearing Outcomes (Ongoing Case)</relationshipLabel>
    <relationshipName>Outcomes_Ongoing_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__Party__c/vlocity_ps__Party__c.object-meta.xml
<CustomObject>
    <description>A party is an individual, business, government entity, household, association, or other entity represented by one or more individuals. In Vlocity applications, each account, contact, and household tracked in the system is also tracked as a party.
The party object holds minimal information, but extends Salesforce to support business-to-consumer (B2C) and business-to-business-to-consumer (B2B2C) practices in addition to business-to-business (B2B) practices.</description>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__Party__c/fields/vlocity_ps__ContactId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the primary Contact identified as this Party when the party is a Contact. Where possible use Contact.PartyId__c instead of this field to determine the Party which identifies any given Contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Party</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/vlocity_ps__PSCasePartyRelationship__c.object-meta.xml
<CustomObject>
    <description>An object to hold the relationships between parties and benefit cases</description>
    <label>Benefit Case Party Relationship</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Case Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PartyId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyId__c</fullName>
    <label>Client</label>
    <referenceTo>vlocity_ps__Party__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PSCaseId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PSCaseId__c</fullName>
    <label>Benefit Case</label>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHandler.cls
public class AttachmentTriggerHandler {
	public static void contentDocumentAfterInsertHandler(List<Attachment> attachmentList){
       
        List<Attachment> courtHearingOutcomeAttachmentList = new List<Attachment>();
        
        for (Attachment file: attachmentList) {
			courtHearingOutcomeAttachmentList.add(file);

        if(!courtHearingOutcomeAttachmentList.isEmpty())
            sendCourtHearingOutcomeEmail(courtHearingOutcomeAttachmentList);
    	}
	}
    public static void sendCourtHearingOutcomeEmail(List<Attachment> attachmentList) {
		List<EmailTemplate> templates = [SELECT Id, Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Court_Hearing_Outcome'];
        map<id,Attachment>  mapx= new  map<id,Attachment>();
        List<vlocity_ps__Party__c> partyList = new List<vlocity_ps__Party__c>();
        List<Contact> contactList = new List<Contact>();
        for(Attachment file:attachmentList){
            mapx.put(file.ParentId,file);
        }
        // Hearing Outcome
        Map<id,Court_Hearing_Outcome__c> outcomes =new Map<id,Court_Hearing_Outcome__c>([Select Id, Ongoing_Case__c from Court_Hearing_Outcome__c where Id in :mapx.keySet()]);
        for(Id key : outcomes.keySet()){
            Court_Hearing_Outcome__c outcome = outcomes.get(key);
            // get Benefit Case Party Relationships id given ongoing_case (benefit case ID)
            Map<id, vlocity_ps__PSCasePartyRelationship__c> parties = new Map<id, vlocity_ps__PSCasePartyRelationship__c>([Select Id, vlocity_ps__PartyId__c FROM vlocity_ps__PSCasePartyRelationship__c WHERE vlocity_ps__PSCaseId__c=:outcome.Ongoing_Case__c]);
        	
            for(Id key2 : parties.keySet()){
            	vlocity_ps__PSCasePartyRelationship__c BCPRelationship = parties.get(key2);
                // get contact Id given party Id
                partyList.add([Select Id, vlocity_ps__ContactId__c FROM vlocity_ps__Party__c WHERE Id =:BCPRelationship.vlocity_ps__PartyId__c]);
        	}
        }
        
        // Retrieve list of emails to be sent
        for(vlocity_ps__Party__c party : partyList){
            contactList.add([Select Email FROM Contact WHERE Id=:party.vlocity_ps__ContactId__c]);
        }
        
        String[] EmailList;
        for(Contact c : contactList){
            EmailList.add(c.Email);
        }
        
        // Attach files to the message
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        
        for (Attachment file: attachmentList) {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            List<Messaging.EmailFileAttachment> eattachments = new List<Messaging.EmailFileAttachment>();
            
            efa.setFileName(file.Name);
            efa.setBody(file.Body);
            efa.setContentType(file.ContentType);
            eattachments.add(efa);
            message.setFileAttachments(eattachments);
            message.setTemplateId(templates[0].Id);
            message.setSaveAsActivity(false);
            message.setSubject(templates[0].Subject);
            message.setHtmlBody(templates[0].Body);
            //message.setTargetObjectId();
            message.setReplyTo('no-reply@cloudsynapps.com');
            message.setToAddresses(EmailList);
            messages.add(message);
        }
        try {
            Messaging.sendEmail( messages );
        } catch (Exception e) {
            throw e;
        } 
	}
}