force-app/main/default/objects/Case/fields/vlocity_ps__PSCaseId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PSCaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Case</label>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Court_Hearing__c/Court_Hearing__c.object-meta.xml
<CustomObject>
    <label>Court Hearing</label>
    <nameField>
        <label>Court Hearing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Court Hearings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Court_Hearing__c/fields/Ongoing_Case__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ongoing Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>vlocity_ps__Case__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Child Welfare</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Court Hearings (Ongoing Case)</relationshipLabel>
    <relationshipName>Ongoing_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Court_Hearing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Court_Hearing_Outcome__c/Court_Hearing_Outcome__c.object-meta.xml
<CustomObject>
    <label>Court Hearing Outcome</label>
    <nameField>
        <label>Court Hearing Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Court Hearing Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Court_Hearing_Outcome__c/fields/Court_Hearing__c.field-meta.xml
<CustomField>
    <fullName>Court_Hearing__c</fullName>
    <label>Court Hearing</label>
    <referenceTo>Court_Hearing__c</referenceTo>
    <relationshipLabel>Court Hearing Outcomes</relationshipLabel>
    <relationshipName>Court_Hearing_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Court_Hearing_Outcome__c/fields/Ongoing_Case__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ongoing Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>vlocity_ps__Case__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Child Welfare</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Court Hearing Outcomes (Ongoing Case)</relationshipLabel>
    <relationshipName>Outcomes_Ongoing_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__Party__c/vlocity_ps__Party__c.object-meta.xml
<CustomObject>
    <description>A party is an individual, business, government entity, household, association, or other entity represented by one or more individuals. In Vlocity applications, each account, contact, and household tracked in the system is also tracked as a party.
The party object holds minimal information, but extends Salesforce to support business-to-consumer (B2C) and business-to-business-to-consumer (B2B2C) practices in addition to business-to-business (B2B) practices.</description>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__Party__c/fields/vlocity_ps__PartyEntityId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyEntityId__c</fullName>
    <description>This field is used internally to store Ids from different objects. If the party type is contact, this field stores Contact.Id, if it is household, it stores Household__c.Id. Used to provide a link to the source record.</description>
    <label>Party Entity Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/vlocity_ps__PSCasePartyRelationship__c.object-meta.xml
<CustomObject>
    <description>An object to hold the relationships between parties and benefit cases</description>
    <label>Benefit Case Party Relationship</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Case Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PartyEntityId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyEntityId__c</fullName>
    <formula>vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Entity Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PartyId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyId__c</fullName>
    <label>Client</label>
    <referenceTo>vlocity_ps__Party__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PSCaseId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PSCaseId__c</fullName>
    <label>Benefit Case</label>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkHandler.cls
public class ContentDocumentLinkHandler {
	public static void handleAfterInsert(List<ContentDocumentLink> cdlList){
        
        Map<Id, List<Id>> caseHearingOutcomeToAttachmentsMap = new Map<Id, List<Id>>();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        // Iterate on newly created ContentDocumentLinks and create a map of court hearing outcome and its related file attachment ids
        for(ContentDocumentLink cdl : cdlList){
            String objName = cdl.LinkedEntityId.getSObjectType().getDescribe().getName();
            if(objName == 'Court_Hearing_Outcome__c'){
                if(caseHearingOutcomeToAttachmentsMap.containsKey(cdl.LinkedEntityId)){
                    caseHearingOutcomeToAttachmentsMap.get(cdl.LinkedEntityId).add(cdl.ContentDocumentId);
                }else{
                    caseHearingOutcomeToAttachmentsMap.put(cdl.LinkedEntityId, new List<Id>{ cdl.ContentDocumentId });
                }
            }
        }
        
        // If the map is empty then return.        
        if(caseHearingOutcomeToAttachmentsMap.isEmpty())
            return;
        
        // Get the related court hearing outcome records whose status is closed
        List<Court_Hearing_Outcome__c> courtHearingOutcomeList = [Select Id,Ongoing_Case__c From Court_Hearing_Outcome__c 
                                                                  Where Id IN :caseHearingOutcomeToAttachmentsMap.keySet() AND
                                                                  Court_Hearing__r.Status__c = 'Closed'];
        
        Map<Id, Id> benefitCaseToCourtHearingOutMap = new Map<Id, Id>();
        Set<Id> contectDocIds = New Set<Id>();
        
        if(!courtHearingOutcomeList.isEmpty()){
            
            // Create a map of Benefit Case with court hearing outcomes as benefit case is the common entity between 
            // court hearing outcome and Benefit Case Party Relationship
            for(Court_Hearing_Outcome__c cho : courtHearingOutcomeList){
                benefitCaseToCourtHearingOutMap.put(cho.Ongoing_Case__c, cho.Id);
                contectDocIds.addAll(caseHearingOutcomeToAttachmentsMap.get(cho.Id));
            }
            
            Map<Id, ContentVersion> fileAttchmentMap = new Map<Id, ContentVersion>();
            
            // Get all the attached file data and map it with the content document Id
            for (ContentVersion cversion : [SELECT ContentDocumentId, title, PathOnClient, FileType, versiondata FROM contentversion WHERE ContentDocumentId IN :contectDocIds]){
                fileAttchmentMap.put(cversion.ContentDocumentId, cversion);
            }
            
            // Get all related Benefit Case Party Relationships to whom the email needs to be sent
            List<vlocity_ps__PSCasePartyRelationship__c> benefitCaseRelationshipList = [Select Id, vlocity_ps__PSCaseId__c, 
                                                                                        vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c 
                                                                                        From vlocity_ps__PSCasePartyRelationship__c
                                                                                   		Where vlocity_ps__PSCaseId__c IN :benefitCaseToCourtHearingOutMap.keySet()];
            
            if(!benefitCaseRelationshipList.isEmpty()){
                
                List<Messaging.Emailfileattachment> attachments;
                EmailTemplate emailTemplate = [Select Id From EmailTemplate Where DeveloperName = 'Court_Hearing_Outcome'];
                
                // Iterate over Benefit Case Party Relationships and create a email message along with the attachments
                for(vlocity_ps__PSCasePartyRelationship__c bcr : benefitCaseRelationshipList){
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setTemplateId(emailTemplate.Id);
                    message.setTargetObjectId(bcr.vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c);
                    message.setWhatId(benefitCaseToCourtHearingOutMap.get(bcr.vlocity_ps__PSCaseId__c));
                    
                    attachments = new List<Messaging.Emailfileattachment>();
                    
                    // Create attachments for the email
                    for(Id contDocId : caseHearingOutcomeToAttachmentsMap.get(benefitCaseToCourtHearingOutMap.get(bcr.vlocity_ps__PSCaseId__c))){
                        ContentVersion fileVersion = fileAttchmentMap.get(contDocId);
                        Blob fileData = fileVersion.versiondata;
                        Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                        efa.setBody(fileData);
                        attachments.add(efa);
                    }
                    
                    message.setFileAttachments(attachments);
                    emailList.add(message);
                }
            }
        }       
        
        // Send email along with the attachments
        if(!emailList.isEmpty()){
            try{
                Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
            }catch(Exception e){
                throw e;
            }            
        }
    }
}