force-app/main/default/objects/Court_Hearing__c/Court_Hearing__c.object-meta.xml
<CustomObject>
    <label>Court Hearing</label>
    <nameField>
        <label>Court Hearing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Court Hearings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Court_Hearing__c/fields/Ongoing_Case__c.field-meta.xml
<CustomField>
    <fullName>Ongoing_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ongoing Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>vlocity_ps__Case__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Child Welfare</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Court Hearings (Ongoing Case)</relationshipLabel>
    <relationshipName>Ongoing_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Court_Hearing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_ps__Party__c/vlocity_ps__Party__c.object-meta.xml
<CustomObject>
    <description>A party is an individual, business, government entity, household, association, or other entity represented by one or more individuals. In Vlocity applications, each account, contact, and household tracked in the system is also tracked as a party.
The party object holds minimal information, but extends Salesforce to support business-to-consumer (B2C) and business-to-business-to-consumer (B2B2C) practices in addition to business-to-business (B2B) practices.</description>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__Party__c/fields/vlocity_ps__PartyEntityId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyEntityId__c</fullName>
    <description>This field is used internally to store Ids from different objects. If the party type is contact, this field stores Contact.Id, if it is household, it stores Household__c.Id. Used to provide a link to the source record.</description>
    <label>Party Entity Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/vlocity_ps__PSCasePartyRelationship__c.object-meta.xml
<CustomObject>
    <description>An object to hold the relationships between parties and benefit cases</description>
    <label>Benefit Case Party Relationship</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Case Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PartyEntityId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyEntityId__c</fullName>
    <formula>vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Entity Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PartyId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PartyId__c</fullName>
    <label>Client</label>
    <referenceTo>vlocity_ps__Party__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/vlocity_ps__PSCasePartyRelationship__c/fields/vlocity_ps__PSCaseId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ps__PSCaseId__c</fullName>
    <label>Benefit Case</label>
    <referenceTo>vlocity_ps__Case__c</referenceTo>
    <relationshipLabel>Benefit Case Party Relationships</relationshipLabel>
    <relationshipName>BenefitCasePartyRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CourtHearingHandler.cls
public class CourtHearingHandler {
    public static void handleAfterInsert(List<Court_Hearing__c> chList){
        Map<Id, Id> benefitCaseToCourtHearingMap = new Map<Id, Id>();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(Court_Hearing__c ch : chList){
            if(ch.Status__c == 'Scheduled'){
                benefitCaseToCourtHearingMap.put(ch.Ongoing_Case__c, ch.Id);
            }
        }
        
        List<vlocity_ps__PSCasePartyRelationship__c> benefitCaseRelationshipList = [Select Id, vlocity_ps__PSCaseId__c, vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c From vlocity_ps__PSCasePartyRelationship__c
                                                                                   	Where vlocity_ps__PSCaseId__c IN :benefitCaseToCourtHearingMap.keySet()];
        
        if(!benefitCaseRelationshipList.isEmpty()){
            EmailTemplate emailTemplate = [Select Id From EmailTemplate Where DeveloperName = 'Court_Hearing_Scheduled'];
            for(vlocity_ps__PSCasePartyRelationship__c bcr : benefitCaseRelationshipList){
            	Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setTemplateId(emailTemplate.Id);
                message.setTargetObjectId(bcr.vlocity_ps__PartyId__r.vlocity_ps__PartyEntityId__c);
                message.setWhatId(benefitCaseToCourtHearingMap.get(bcr.vlocity_ps__PSCaseId__c));
                emailList.add(message);
        	}
        }
        
        if(!emailList.isEmpty()){
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
        }
    }
}